version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "69:69"
    networks:
      - mynet
    container_name: Weather-Station-API
    volumes:
      - .:/app
    command: python -u app.py
    links:
      - db
    
  db:
    image: mongo:latest
    container_name: "Weather-Station-DB"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - mynet
    volumes:
      - wsdb_data:/data/db

networks:
  mynet:

volumes:
  wsdb_data: